name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Lint & Formatting Checks
    runs-on: ubuntu-latest

    env:
      SQLX_OFFLINE: true

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Cargo registry and build
        uses: Swatinem/rust-cache@v2

      - name: Install Protobuf Compiler
        run: |
          apt-get update
          apt-get install -y protobuf-compiler

      - name: Compile Protobuf Files
        run: |
          mkdir -p src/target  # Ensure the output directory exists
          protoc --experimental_allow_proto3_optional --rust_out=src/target proto/todo.proto

      # Cargo Clippy
      - name: Cargo Clippy
        run: cargo clippy -- -D warnings
        # Uncomment if you have a specific working directory
        # working-directory: retail-smartops-user-management-service

      # Cargo fmt
      - name: Cargo Fmt
        run: cargo fmt --check
        # Uncomment if you have a specific working directory
        # working-directory: retail-smartops-user-management-service
